import React from 'react';
import './Table.css';

// 请注意两张表格不一样
// index 页面的表格

export default function IndexTable() {

  return (
    <>
      <table border='0' className="index__table">
        <thead>
          <tr>
            <th>#</th>
            <th>客户</th>
            <th>标签</th>
            <th>Inhalant</th>
            <th>拜访</th>
            <th>样品</th>
            <th>医学继续...</th>
            <th>学习午餐会</th>
            <th>文献报告会</th>
            <th>拜访类型</th>
          </tr>
        </thead>
        
        <tbody>
          <tr>
            <td>1</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>2</td>
            <td>luck</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>3</td>
            <td>salim</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Cathy</td>
            <td>1</td>
            <td>10</td>
            <td>2</td>
            <td>0</td>
            <td>3</td>
            <td>1</td>
            <td>7</td>
            <td>3</td>
          </tr>
          
        </tbody>
      </table>
    </>
  )
}